name: Daniel Dittenhafer
description: I am a software engineer, manager, data analyst and consultant with a passion for improving the efficiency of businesses and organizations through data analysis and software automation.
url: http://dwdii.github.io
show_drafts: false